"""
Hierarchical Intent Classifier for SentiNews Dynamic Query Intelligence System.

This is the ENTRY POINT of the entire agentic pipeline.
Every user query passes through this node first, determining:
  - primary_intent: The main category of the query
  - secondary_intent: A supporting sub-category for mixed queries
  - intent_confidence: How certain we are (0.0 - 1.0)
  - query_risk_level: SEBI compliance risk (LOW, MEDIUM, HIGH)
  - complexity_level: Whether to run LIGHT or DEEP analysis
  - requires_live_data: Whether live market APIs should be called
  - extracted_ticker: Best-guess ticker from the query text

ROUTING RULES:
  - confidence < LOW_CONFIDENCE_THRESHOLD (0.65) → GENERALIZED workflow
  - query_risk_level == HIGH → Safe Refusal (no analyst nodes invoked)
  - primary_intent == RESTRICTED_ADVISORY → Immediate educational redirect
"""

import logging
from langchain_core.prompts import ChatPromptTemplate
from langchain_groq import ChatGroq
from pydantic import BaseModel, Field
from typing import Literal, Optional, Dict, Any
from src.core.config import settings
from src.agents.query_risk_scoring import score_advisory_risk, QueryRiskLevel
from src.core.debug_logger import debug_logger

logger = logging.getLogger(__name__)

LOW_CONFIDENCE_THRESHOLD = 0.65

# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------

class IntentClassification(BaseModel):
    """
    Hierarchical intent output from the classifier.
    Drives ALL downstream routing decisions.
    """
    primary_intent: Literal[
        "EDUCATIONAL",
        "COMPANY_OVERVIEW",
        "COMPANY_ANALYSIS",
        "COMPANY_COMPARISON",
        "SECTOR_OUTLOOK",
        "THEME_ANALYSIS",
        "MARKET_OVERVIEW",
        "NEWS_ANALYSIS",
        "TECHNICAL_ANALYSIS",
        "FUNDAMENTAL_ANALYSIS",
        "VALUATION_ANALYSIS",
        "RISK_ANALYSIS",
        "RESTRICTED_ADVISORY",
        "GENERALIZED",
        "UNKNOWN",
        
        # Backward compatibility archetypes
        "STOCK_ANALYSIS",
        "COMPARISON",
        "STOCK_MOVEMENT",
        "PEER_COMPARISON",
        "EARNINGS_REPORT"
    ] = Field(description="Primary classification of the user query")
    
    planner_layout: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Configuration layout generated by ResponsePlanner")

    secondary_intent: Optional[Literal[
        "NEWS",                  # News-driven component
        "FUNDAMENTAL",           # Valuation or financial health sub-query
        "TECHNICAL",             # Chart/price action sub-query
        "MACRO",                 # Macro overlay needed
        "NONE",
    ]] = Field(default="NONE", description="Supporting secondary classification for mixed queries")

    intent_confidence: float = Field(
        ge=0.0, le=1.0,
        description="Confidence score in the classification (0.0 = unknown, 1.0 = certain)"
    )

    query_risk_level: Literal["LOW", "MEDIUM", "HIGH"] = Field(
        description=(
            "LOW: Educational/analytical query. "
            "MEDIUM: Borderline advisory language. "
            "HIGH: Direct investment advice request, guarantees, or SEBI-restricted language."
        )
    )

    query_risk_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Pattern-based advisory risk score used to tune compliance strictness"
    )

    complexity_level: Literal["LIGHT", "DEEP"] = Field(
        description=(
            "LIGHT: Simple factual/movement query. Run only 1-2 relevant agents. "
            "DEEP: Full synthesis required. Run all analyst nodes."
        )
    )

    requires_live_data: bool = Field(
        description="False for EDUCATIONAL queries — no live API calls needed"
    )

    extracted_ticker: Optional[str] = Field(
        default=None,
        description="Best-guess NSE ticker symbol extracted from the query (e.g. TCS, RELIANCE). None if not applicable."
    )

    company: Optional[str] = Field(
        default=None,
        description="Resolved company name"
    )

    entity_collection: Optional[Dict[str, Any]] = Field(
        default=None,
        description="The resolved EntityCollection serialized to dict"
    )

    classification_reasoning: str = Field(
        description="Short 1-2 sentence explanation of why this classification was chosen"
    )


# ---------------------------------------------------------------------------
# LLM Setup
# ---------------------------------------------------------------------------

llm_classifier = ChatGroq(
    temperature=0.0,   # Zero temperature: classification must be deterministic
    model_name="llama-3.1-8b-instant",
    api_key=settings.GROQ_API_KEY
) if settings.GROQ_API_KEY else None

CLASSIFIER_SYSTEM_PROMPT = """You are a specialized Financial Query Intent Classifier for an Indian stock market AI platform.

Analyze the User Query and the Resolved Entities, and output a structured intent classification JSON.

PRIMARY INTENT TAXONOMY:
- EDUCATIONAL: Plain explanations of financial metrics, concepts, or terms (e.g. "Explain ROE", "What is RSI?", "Concept of P/E ratio").
- COMPANY_OVERVIEW: Basic profile of a company, business model summary, or general overview (e.g. "How is TCS?", "What does Tesla do?").
- COMPANY_ANALYSIS: Comprehensive stock analysis deep-dive (e.g. "Analyze NVIDIA").
- COMPANY_COMPARISON: Head-to-head comparison of two or more companies (e.g. "Compare Infosys and TCS").
- SECTOR_OUTLOOK: Outlook, trends, growth, or challenges of an entire industry/sector (e.g. "Indian IT sector outlook", "Banking sector overview").
- THEME_ANALYSIS: Technology adoption, industry themes, or mega-trends (e.g. "Cloud adoption in Indian IT", "AI adoption in healthcare").
- MARKET_OVERVIEW: General stock market indexes, macro updates, or breadth (e.g. "Nifty today", "Stock market update").
- NEWS_ANALYSIS: Recent news events or headline analysis for a company (e.g. "Latest news on Reliance").
- TECHNICAL_ANALYSIS: Technical indicators, charts, support/resistance, momentum, moving averages (e.g. "Technical analysis of Nvidia").
- FUNDAMENTAL_ANALYSIS: Balance sheets, financial ratios, cash flows, margins (e.g. "Analyze Tesla fundamentals").
- VALUATION_ANALYSIS: Valuation multiples, pricing assessment (e.g. "PE ratio of Apple", "Is TCS overvalued?").
- RISK_ANALYSIS: Specific risks, threats, or downside risks of a company (e.g. "Tesla risk factors").
- RESTRICTED_ADVISORY: Asking for investment tips or buy/sell/hold decisions (e.g. "Should I buy Tesla?").
- UNKNOWN: Falls back to general analysis if completely unclear.

RISK LEVEL RULES:
- HIGH: Query contains "should I buy/sell", "guaranteed", "sure shot", "tip", "multibagger today", asking for direct trade signals
- MEDIUM: Query uses language like "is it worth investing", "is it a good time", borderline advisory
- LOW: Analytical, educational, or movement analysis queries

COMPLEXITY RULES:
- DEEP: Stock analysis, comparison queries
- LIGHT: Movement queries, educational, macro, sentiment-only, market overview

LIVE DATA RULES:
- requires_live_data = false ONLY for EDUCATIONAL intent
- requires_live_data = true for everything else
"""

def _make_intent_decision(query: str, primary_intent: str, confidence: float, reasoning: str, collection, detected_entities_str: str) -> dict:
    query_lower = query.lower()
    
    # Step 5: Educational queries must never inject a company. Explain ROE -> Ticker: None. Skip live calls.
    if primary_intent == "EDUCATIONAL":
        ticker = None
        company_name = None
        policy_name = "EDUCATIONAL"
        reason = "Educational query. Ticker override to None."
    
    # Step 6: Sector queries must never become company queries. Indian IT sector outlook -> Ticker: None.
    elif primary_intent == "SECTOR_OUTLOOK" or "sector" in query_lower or "industry" in query_lower:
        primary_intent = "SECTOR_OUTLOOK"
        ticker = None
        company_name = None
        policy_name = "SECTOR_OUTLOOK"
        reason = "Sector outlook query. Ticker override to None."
        
    elif primary_intent == "THEME_ANALYSIS":
        ticker = None
        company_name = None
        policy_name = "THEME_ANALYSIS"
        reason = "Theme analysis query. Ticker override to None."
        
    else:
        # Standard company-related queries
        ticker = collection.primary_ticker if collection else None
        company_name = collection.primary.company_name if (collection and collection.primary) else None
        policy_name = primary_intent
        reason = reasoning
        
    # Get retrieval policy from policy registry
    from src.agents.retrieval_policy import get_policy
    policy = get_policy(policy_name)
    
    # IntentDecision layout
    return {
        "intent": primary_intent,
        "confidence": confidence,
        "reason": reason,
        "retrieval_policy": policy.description,
        "ticker": ticker,
        "company": company_name
    }

classifier_prompt = ChatPromptTemplate.from_messages([
    ("system", CLASSIFIER_SYSTEM_PROMPT),
    ("user", "{query}")
])


# ---------------------------------------------------------------------------
# Node Function
# ---------------------------------------------------------------------------

async def intent_classifier_node(state: dict) -> dict:
    """
    LangGraph node: Classifies the user query and populates intent fields in state.
    This is always the FIRST node in the graph.
    
    Performs:
    1. Query risk scoring (SEBI compliance check)
    2. Entity extraction and pre-classification
    3. LLM intent classification (with entity details)
    4. Decision layer validation (Ticker overrides for educational/sector/theme query types)
    5. Layout planning
    6. Comprehensive formatted debug logging
    """
    query = state.get("query", "")

    # Hard-coded fast path: empty query
    if not query.strip():
        logger.warning("Empty query received by intent classifier.")
        return {
            "intent": {
                "primary_intent": "GENERALIZED",
                "secondary_intent": "NONE",
                "intent_confidence": 0.0,
                "query_risk_level": "LOW",
                "query_risk_score": 0.0,
                "complexity_level": "LIGHT",
                "requires_live_data": False,
                "extracted_ticker": None,
                "classification_reasoning": "Empty query received.",
                "planner_layout": ResponsePlanner.get_layout("GENERALIZED")
            }
        }

    # ========== STEP 1: QUERY RISK SCORING ==========
    risk_level, risk_score, detected_patterns = score_advisory_risk(query)

    # ========== STEP 2: ENTITY EXTRACTION AND PRE-CLASSIFICATION ==========
    from src.services.entity_resolution_pipeline import EntityResolutionPipeline
    collection = EntityResolutionPipeline.resolve_entities_sync(query)
    
    candidates = EntityResolutionPipeline._extract_candidates(query)
    detected_entities_list = []
    has_company = False
    has_sector = False
    has_theme = False
    has_metric = False
    has_indicator = False
    
    for cand in candidates:
        ent_type = EntityResolutionPipeline._classify_candidate(cand, query)
        detected_entities_list.append(f"{cand} (Type: {ent_type})")
        if ent_type in ("company", "ticker"):
            has_company = True
        elif ent_type == "sector":
            has_sector = True
        elif ent_type in ("technology_concept", "industry_theme"):
            has_theme = True
        elif ent_type == "financial_metric":
            has_metric = True
        elif ent_type == "technical_indicator":
            has_indicator = True
            
    detected_entities_str = ", ".join(detected_entities_list) if detected_entities_list else "None"
    
    # Enforce priority ticker if present in state
    if state.get("ticker"):
        from src.services.entity_resolver import EntityResolver
        sym = state["ticker"].upper().strip()
        name = EntityResolver._ticker_to_company.get(sym) or sym
        from src.services.entity_models import ResolvedEntity
        existing = collection.get_entity(sym)
        if not existing:
            new_entity = ResolvedEntity(
                ticker=sym,
                company_name=name,
                confidence=1.00,
                resolution_source="CONVERSATION_MEMORY",
                aliases=[sym.lower(), name.lower()],
                is_primary=True,
                query_span=sym
            )
            entities = [new_entity] + [e for e in collection.entities if e.ticker != sym]
            from src.services.entity_models import EntityCollection
            collection = EntityCollection(
                entities=entities,
                query=query,
                resolution_mode="SINGLE" if len(entities) == 1 else "MULTI",
                total_found=len(entities),
                resolution_warnings=collection.resolution_warnings
            )
            has_company = True

    # ========== STEP 3: LLM INTENT CLASSIFICATION ==========
    classification = None
    if llm_classifier:
        try:
            structured_llm = llm_classifier.with_structured_output(IntentClassification)
            chain = classifier_prompt | structured_llm
            
            user_msg = f"User Query: {query}\nResolved Entities: {detected_entities_str}\n\nClassify this query now."
            classification = await chain.ainvoke({"query": user_msg})
        except Exception as e:
            logger.error(f"Structured LLM classification failed: {e}. Falling back to rule-based classification.")

    if not classification:
        query_lower = query.lower()
        if "explain" in query_lower or "what is" in query_lower or has_metric or has_indicator:
            primary = "EDUCATIONAL"
        elif "compare" in query_lower or "vs" in query_lower:
            primary = "COMPANY_COMPARISON"
        elif "sector" in query_lower or "industry" in query_lower or has_sector:
            primary = "SECTOR_OUTLOOK"
        elif "adoption" in query_lower or "trend" in query_lower or has_theme:
            primary = "THEME_ANALYSIS"
        elif "technical" in query_lower or "chart" in query_lower or "momentum" in query_lower:
            primary = "TECHNICAL_ANALYSIS"
        elif "fundamental" in query_lower or "fundamentals" in query_lower:
            primary = "FUNDAMENTAL_ANALYSIS"
        elif "valuation" in query_lower or "pe" in query_lower or "peg" in query_lower:
            primary = "VALUATION_ANALYSIS"
        elif "risk" in query_lower or "threat" in query_lower:
            primary = "RISK_ANALYSIS"
        elif "news" in query_lower or "why is" in query_lower or "today" in query_lower:
            primary = "NEWS_ANALYSIS"
        elif has_company:
            primary = "COMPANY_OVERVIEW"
        else:
            primary = "GENERALIZED"
            
        classification = IntentClassification(
            primary_intent=primary,
            secondary_intent="NONE",
            intent_confidence=0.7,
            query_risk_level=risk_level.value,
            query_risk_score=risk_score,
            complexity_level="DEEP" if primary in ("COMPANY_COMPARISON", "COMPANY_ANALYSIS") else "LIGHT",
            requires_live_data=False if primary == "EDUCATIONAL" else True,
            extracted_ticker=collection.primary_ticker if collection else None,
            company=collection.primary.company_name if (collection and collection.primary) else None,
            classification_reasoning="Rule-based fallback classification."
        )

    # Enforce SEBI risk limits
    if risk_level == QueryRiskLevel.HIGH:
        classification.query_risk_level = "HIGH"
        classification.query_risk_score = risk_score
        classification.primary_intent = "RESTRICTED_ADVISORY"
        classification.complexity_level = "LIGHT"
        classification.requires_live_data = False

    # Low confidence override
    if classification.intent_confidence < LOW_CONFIDENCE_THRESHOLD:
        classification.primary_intent = "GENERALIZED"
        classification.complexity_level = "DEEP"

    # ========== STEP 4: INTENT DECISION LAYER ==========
    decision = _make_intent_decision(
        query=query,
        primary_intent=classification.primary_intent,
        confidence=classification.intent_confidence,
        reasoning=classification.classification_reasoning,
        collection=collection,
        detected_entities_str=detected_entities_str
    )
    
    # Apply decided overrides back to classification
    classification.primary_intent = decision["intent"]
    classification.extracted_ticker = decision["ticker"]
    classification.company = decision["company"]
    classification.requires_live_data = False if classification.primary_intent == "EDUCATIONAL" else True
    
    if not classification.extracted_ticker:
        classification.entity_collection = {"entities": [], "query": query, "resolution_mode": "EDUCATIONAL", "total_found": 0}
    else:
        classification.entity_collection = collection.to_dict()

    # Generate planner layout
    from src.agents.planner import ResponsePlanner
    classification.planner_layout = ResponsePlanner.get_layout(classification.primary_intent)

    # ========== STEP 5: SECTOR/COMPANY VALIDATION GATE ==========
    if classification.extracted_ticker:
        from src.core.middleware import validate_query_multiple_companies
        try:
            validate_query_multiple_companies(query, classification.primary_intent, entity_collection=classification.entity_collection)
        except ValueError as e:
            raise e

    # ========== STEP 6: IMPROVED DEBUG LOGGING ==========
    detected_entity_type = "None"
    if has_company:
        detected_entity_type = "Company"
    elif has_sector:
        detected_entity_type = "Sector"
    elif has_theme:
        detected_entity_type = "Theme"
    elif has_metric:
        detected_entity_type = "Financial Metric"
    elif has_indicator:
        detected_entity_type = "Technical Indicator"

    print(
        f"\n================================================\n"
        f"INTENT CLASSIFICATION\n"
        f"================================================\n"
        f"Query:\n{query}\n"
        f"Detected Entity:\n{detected_entity_type}\n"
        f"Intent:\n{classification.primary_intent}\n"
        f"Confidence:\n{classification.intent_confidence:.2f}\n"
        f"Retrieval Policy:\n{decision['retrieval_policy']}\n"
        f"Reason:\n{decision['reason']}\n"
        f"================================================\n"
    )

    debug_logger.log_intent_classification(
        query=query,
        primary_intent=classification.primary_intent,
        secondary_intent=classification.secondary_intent,
        intent_confidence=classification.intent_confidence,
        query_risk_level=classification.query_risk_level,
        complexity_level=classification.complexity_level,
        extracted_ticker=classification.extracted_ticker,
        reasoning=classification.classification_reasoning
    )

    return {"intent": classification.model_dump()}
